name: nextroute_2026
description: Public Transportation Mobile Application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  google_fonts: ^6.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/stops.txt
    - assets/routes.txt
    - assets/ridership.csv