name: nextroute_assignment
description: Public Transportation Mobile Application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  csv: ^6.0.0
  cupertino_icons: ^1.0.8
  flutter_local_notifications: ^21.0.0
  google_fonts: ^8.2.1
  http: ^1.1.0
  shared_preferences: ^2.5.5
  supabase_flutter: ^2.8.0
  flutter_map: ^8.3.1
  flutter_map_location_marker: ^10.3.0
  gtfs_realtime_bindings: ^1.2.0
  latlong2: ^0.9.1
  location: ^10.0.2
  permission_handler: ^12.0.3
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/gtfs/rail/
    - assets/gtfs/bus/
    - assets/gtfs/mrt_feeder/
