name: nextroute_assignment
description: Public Transportation Mobile Application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0          # <--- Make sure this line exists
  google_fonts: ^8.2.1

flutter:
  uses-material-design: true
  assets:
    - assets/ridership.csv
    - assets/gtfs/rail/
    - assets/gtfs/bus/
    - assets/gtfs/mrt_feeder/